version: '3'
networks:
  mpstats:
services:
  app-admin:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - clickhouse-server
    networks:
      - mpstats

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./db:/var/lib/clickhouse
    ulimits:
      nofile: 262144
    networks:
      - mpstats
  php:
    build:
      context: .
      dockerfile: ./Docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - mpstats

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php